# Site settings
title:          Logical Selection 2.0
description:    A blog about productivity, achievement, overcoming failure, and everything in between. Postmortems and how-tos on life, career, and academics.
url:            "https://susanshu.com"

# Google Analytics
google_analytics: UA-139221907-1

# Author
author:
  name:         Shu
  url:          https://susanshu.com
  email:        foo@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:categories/:year/:month/:day/:title

pagination:
  enabled: true
  per_page: 5
  parmalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
